export const LoginConstants = {
  LOGIN_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_USER_FAILURE',
};

export const RegistrationConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
};
